const gameName = new String("thevaishndra ");
// console.log(gameName[0]);
// console.log(gameName.__proto__);
console.log(gameName.length);
console.log(gameName.toUpperCase());
console.log(gameName.charAt(8));
console.log(gameName.indexOf("d"));
console.log(gameName.substring(4, 10));
console.log(gameName.trim());
console.log(gameName.replace("the", "best"));